WIP: Mount the input paths to same paths inside container. This way we do not have to modify the paths.

diff --git a/docker/moma_preprocess b/docker/moma_preprocess
--- a/docker/moma_preprocess
+++ b/docker/moma_preprocess
@@ -26,6 +26,26 @@ echo ""
 
 CMD_ARGUMENTS=""
 
+function get_directory_path {
+    # This function takes the path of a file or directory. If file-path is passed it returns the path to the parent
+    # directory. If a directory is passed, it returns the path to the directory itself.
+    local TARGET_PATH=$1
+#    echo "In get_directory_path: ${TARGET_PATH}"
+    if [[ -d "$TARGET_PATH" ]]; then
+      echo "$TARGET_PATH"
+      return 0
+    elif [[ -f "$TARGET_PATH" ]]; then
+      RET=$(dirname "$TARGET_PATH")
+#      echo "RET: ${RET}"
+      echo "$RET"
+      return 0
+    else
+      # an invalid value was passed
+      echo "ERROR in get_directory_path: The path that was passed is neither a file or directory: ${TARGET_PATH}"
+      exit 1
+    fi
+}
+
 # This while loop captures paths that will be mount directories to the container.
 # Other arguments are appended to the variable CMD_ARGUMENTS, which is passed as command line argument to the container.
 while :
@@ -33,15 +53,24 @@ do
   echo "Argument $1: $2"
   case "$1" in
     -i )
-      input_path="$2"
+#      input_path="$2"
+      input_path=$(get_directory_path "$2")
+      echo "input_path: ${input_path}"
+      CMD_ARGUMENTS="${CMD_ARGUMENTS} $1 $2"
+#      get_directory_path "$2"
+#      echo
       shift 2
       ;;
     -o )
-      output_path="$2"
+#      output_path="$2"
+      output_path=$(get_directory_path "$2")
+      CMD_ARGUMENTS="${CMD_ARGUMENTS} $1 $2"
       shift 2
       ;;
     --log )
-      log_path="$2"
+#      log_path="$2"
+      log_path=$(get_directory_path "$2")
+      CMD_ARGUMENTS="${CMD_ARGUMENTS} $1 $2"
       shift 2
       ;;
     -- )
@@ -73,6 +102,8 @@ echo "Option log_path: $log_path"
 
 #docker run --rm --mount type=bind,src="${input_path}",target=${container_input_path} --mount type=bind,src="${output_path}",target="${container_output_path}" "${docker_image_name}" "${CMD_ARGUMENTS}"
 #docker run -it --entrypoint /bin/bash --rm --mount type=bind,src="${input_path}",target=${container_input_path} --mount type=bind,src="${output_path}",target="${container_output_path}" "${docker_image_name}"
+
+echo docker run -it --entrypoint /bin/bash --rm --mount type=bind,src="${input_path}",target="${input_path}" --mount type=bind,src="${output_path}",target="${output_path}" --mount type=bind,src="${log_path}",target="${log_path}" "${docker_image_name}"
 
 #echo "$DOCKER_COMMAND"
 #eval "$DOCKER_COMMAND"
