Remove external dependencies. Start work to refactor code for pulling singularity image.

diff --git a/docker/moma_preprocess b/docker/moma_preprocess
--- a/docker/moma_preprocess
+++ b/docker/moma_preprocess
@@ -2,14 +2,14 @@
 
 ###
 # This script parses the command options for the preprocessing and calls the docker container for running the
-# containerized preprocessing instance.
+# containerized preprocessing instance. It support Docker and Singularity container engines. Singularity engine will be
+# preferred, if available.
 ###
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-source "${DIR}/helpers.sh"
-
-docker_image_name=$(get_image_tag)
+#source "${DIR}/helpers.sh"
+#source "${DIR}/functions.sh"
 
 SHORT=i:,o:,p:,r:
 LONG=tmax:,roi_boundary_offset_at_mother_cell:,gl_detection_template_path:,normalization_config_path:,normalization_region_offset:,frames_to_ignore:,image_registration_method:,forced_intensity_normalization_range:,log:
@@ -33,7 +33,7 @@ function get_directory_path {
       return 0
     else
       # an invalid value was passed
-      echo "ERROR in get_directory_path: The path that was passed is neither a file or directory: ${TARGET_PATH}"
+      echo "ERROR: Path does not exist: ${TARGET_PATH}"
       exit 1
     fi
 }
@@ -74,22 +74,53 @@ do
   esac
 done
 
+echo "running container"
+#echo "SINGULARITY_CONTAINER_DIR: ${SINGULARITY_CONTAINER_DIR}"
+#SINGULARITY_CONTAINER_NAME="${CONTAINER_NAME//\//_}"
+#echo "SINGULARITY_CONTAINER_NAME: ${SINGULARITY_CONTAINER_NAME}"
+#SINGULARITY_CONTAINER_FILENAME="${CONTAINER_NAME//\//_}_${VERSION}.sif"
+#echo "SINGULARITY_CONTAINER_FILENAME: ${SINGULARITY_CONTAINER_FILENAME}"
+#SINGULARITY_CONTAINER_PATH="${SINGULARITY_CONTAINER_DIR}/${SINGULARITY_CONTAINER_FILENAME}"
+#echo "SINGULARITY_CONTAINER_PATH: ${SINGULARITY_CONTAINER_PATH}"
+#
+#echo "EXITING"; exit 1
+
 # Use docker if it available
 if command -v docker &> /dev/null
 then
-    docker pull "${docker_image_name}"
-    docker run --rm --mount type=bind,src="${input_path}",target="${input_path}" --mount type=bind,src="${gl_detection_template_path}",target="${gl_detection_template_path}" --mount type=bind,src="${output_path}",target="${output_path}" --mount type=bind,src="${log_path}",target="${log_path}" "${docker_image_name}" "${CMD_ARGUMENTS}"
+    docker pull "${CONTAINER_TAG}"
+    docker run --rm --mount type=bind,src="${input_path}",target="${input_path}" --mount type=bind,src="${gl_detection_template_path}",target="${gl_detection_template_path}" --mount type=bind,src="${output_path}",target="${output_path}" --mount type=bind,src="${log_path}",target="${log_path}" "${CONTAINER_TAG}" "${CMD_ARGUMENTS}"
 elif command -v singularity &> /dev/null
 then
-    echo "Running preprocessing using Singularity container."
-    SINGULARITY_CONTAINER_DIR="$HOME/singularity_images"
-    echo "${SINGULARITY_CONTAINER_DIR}"
-    echo "$(get_singularity_container_name)"
-    SINGULARITY_CONTAINER_PATH="${SINGULARITY_CONTAINER_DIR}/$(get_singularity_container_name)"
-    echo "${SINGULARITY_CONTAINER_PATH}"
-    mkdir "${SINGULARITY_CONTAINER_DIR}"
+#    echo "Running preprocessing using Singularity container."
+#    SINGULARITY_CONTAINER_DIR="$HOME/singularity_images"
+#    echo "${SINGULARITY_CONTAINER_DIR}"
+#    echo "$(get_singularity_container_name)"
+##    SINGULARITY_CONTAINER_PATH="${SINGULARITY_CONTAINER_DIR}/$(get_singularity_container_name)"
+#    SINGULARITY_CONTAINER_FILENAME="${CONTAINER_NAME}_${VERSION}.sif"
+#    SINGULARITY_CONTAINER_PATH="${SINGULARITY_CONTAINER_DIR}/${SINGULARITY_CONTAINER_FILENAME}"
 
-    singularity pull --dir="${SINGULARITY_CONTAINER_DIR}" "docker://${docker_image_name}"
-    singularity run --bind "${input_path}":"${input_path}" --bind "${gl_detection_template_path}":"${gl_detection_template_path}" --bind "${output_path}":"${output_path}" --bind "${log_path}":"${log_path}" "${SINGULARITY_CONTAINER_PATH}" "${CMD_ARGUMENTS}"
-#docker run --rm --mount type=bind,src="${input_path}",target="${input_path}" --mount type=bind,src="${gl_detection_template_path}",target="${gl_detection_template_path}" --mount type=bind,src="${output_path}",target="${output_path}" --mount type=bind,src="${log_path}",target="${log_path}" "${docker_image_name}" "${CMD_ARGUMENTS}"
+#    echo "SINGULARITY_CONTAINER_DIR: ${SINGULARITY_CONTAINER_DIR}"
+    SINGULARITY_CONTAINER_NAME="${CONTAINER_NAME//\//_}"
+#    echo "SINGULARITY_CONTAINER_NAME: ${SINGULARITY_CONTAINER_NAME}"
+    SINGULARITY_CONTAINER_FILENAME="${CONTAINER_NAME//\//_}_${VERSION}.sif"
+#    echo "SINGULARITY_CONTAINER_FILENAME: ${SINGULARITY_CONTAINER_FILENAME}"
+    SINGULARITY_CONTAINER_FILE_PATH="${SINGULARITY_CONTAINER_DIR}/${SINGULARITY_CONTAINER_FILENAME}"
+#    echo "SINGULARITY_CONTAINER_PATH: ${SINGULARITY_CONTAINER_PATH}"
+
+#    echo "${SINGULARITY_CONTAINER_PATH}"
+    if [[ ! -d ${SINGULARITY_CONTAINER_DIR} ]]; then
+      mkdir "${SINGULARITY_CONTAINER_DIR}"
+    fi
+
+    if [[ ! -f "${SINGULARITY_CONTAINER_FILE_PATH}" ]]; then
+      singularity pull "${SINGULARITY_CONTAINER_FILE_PATH}" "docker://${CONTAINER_TAG}"
+    fi
+    singularity run --bind "${input_path}":"${input_path}" --bind "${gl_detection_template_path}":"${gl_detection_template_path}" --bind "${output_path}":"${output_path}" --bind "${log_path}":"${log_path}" "${SINGULARITY_CONTAINER_FILE_PATH}" "${CMD_ARGUMENTS}"
+#docker run --rm --mount type=bind,src="${input_path}",target="${input_path}" --mount type=bind,src="${gl_detection_template_path}",target="${gl_detection_template_path}" --mount type=bind,src="${output_path}",target="${output_path}" --mount type=bind,src="${log_path}",target="${log_path}" "${CONTAINER_TAG}" "${CMD_ARGUMENTS}"
+else
+    printf "ERROR: No container engine was found. Check that Singularity or Docker are correctly configured."
+    exit 1
 fi
+
+exit 0
